### ISSUE TITLE
A small question about the implemtation of RND

### ISSUE THREAD

**Issue by elonhe1990** [billhhh/RDP#3]
大佬你好，你的工作非常精彩，看完你的工作，我受到了很大的启发。我想请教一下跑RND baseline的问题。在你的代码中，按照我的理解是不是只要把在[Line](https://github.com/billhhh/RDP/blob/e3994e7720d0394863e39ecda641face3137bae8/RDP-Anomaly/model.py#L177)和[Line](https://github.com/billhhh/RDP/blob/e3994e7720d0394863e39ecda641face3137bae8/RDP-Anomaly/model.py#L207)中的loss里面的pair_wise_loss去掉就可以了就好？按照这个思路来操作的话，我得到了下面的结果：

在apascal数据集上
RDP：AUC-ROC: 0.8264, AUC-PR:0.0419。这个结果和论文的结果是一致的
RND(原来代码中去掉pairwise loss)：**AUC-ROC: 0.8251, AUC-PR:0.0386**。但是这个RND的复现结果和RDP结果很接近，但是和论文RND的结果差别比较大（论文中的Table1&2结果是AUC-ROC: 0.685, AUC-PR:0.021）。

我们这样的实现RND改法是不是对的？有没有遗漏什么细节？

期待你的回复。谢谢！！！！

**Comment by elonhe1990** [comment]
我再认真检查了一下，我认为我代码修改的方式应该是正确的。多次重复实验的结果是 

AUC-ROC: 0.8247, AUC-PR:0.0350
AUC-ROC: 0.8266, AUC-PR:0.0395
AUC-ROC: 0.8230, AUC-PR:0.0391

和之前给的结果（**AUC-ROC: 0.8251, AUC-PR:0.0386**）基本一样。还是没有找到具体问题出现在哪里，您方便git一下实现RND的代码吗？谢谢。

**Comment by billhhh** [comment]
> 我再认真检查了一下，我认为我代码修改的方式应该是正确的。多次重复实验的结果是
> 
> AUC-ROC: 0.8247, AUC-PR:0.0350
> AUC-ROC: 0.8266, AUC-PR:0.0395
> AUC-ROC: 0.8230, AUC-PR:0.0391
> 
> 和之前给的结果（**AUC-ROC: 0.8251, AUC-PR:0.0386**）基本一样。还是没有找到具体问题出现在哪里，您方便git一下实现RND的代码吗？谢谢。

抱歉才看到这个 issue，论文中 rnd model 只是看单网络的 Distillation 情况，没有加树过滤。树过滤也是提出 rdp 模型的一部分。另外单比 rdp 和 rnd，因为加了 pair-wise loss 应该也有一定提升。论文是跑10次取平均的结果。

希望对你有帮助。

**Comment by elonhe1990** [comment]
感谢你的回复。我现在去掉了树过滤之后，可以得到你文章中的RND数值结果。感激~

**Comment by billhhh** [comment]
> 感谢你的回复。我现在去掉了树过滤之后，可以得到你文章中的RND数值结果。感激~

客气~
